# Generated by Django 6.0 on 2026-01-03 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المؤلف')),
                ('biography', models.TextField(blank=True, verbose_name='السيرة الذاتية')),
            ],
            options={
                'verbose_name': 'مؤلف',
                'verbose_name_plural': 'المؤلفين',
                'db_table': 'books_author',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='core.category', verbose_name='التصنيف الرئيسي')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'db_table': 'books_category',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الكتاب')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='الرقم التسلسلي (ISBN)')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة النشر')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='عدد النسخ الكلي')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='النسخ المتاحة')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/', verbose_name='صورة الغلاف')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('borrowed', 'مستعار'), ('reserved', 'محجوز'), ('lost', 'مفقود')], default='available', max_length=20, verbose_name='الحالة')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(db_table='books_book_authors', related_name='books', to='core.author', verbose_name='المؤلفين')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'كتاب',
                'verbose_name_plural': 'الكتب',
                'db_table': 'books_book',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'مدير'), ('librarian', 'أمين مكتبة'), ('assistant', 'مساعد')], default='librarian', max_length=20, verbose_name='الدور الوظيفي')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم (حساب الدخول)')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
                'db_table': 'employees_employee',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('membership_type', models.CharField(choices=[('student', 'طالب'), ('teacher', 'معلم'), ('visitor', 'زائر')], default='student', max_length=20, verbose_name='نوع العضوية')),
                ('membership_level', models.CharField(choices=[('regular', 'عادي'), ('silver', 'فضي'), ('gold', 'ذهبي')], default='regular', max_length=20, verbose_name='مستوى العضوية')),
                ('max_borrow_limit', models.PositiveIntegerField(default=3, verbose_name='الحد الأقصى للإعارة')),
                ('current_borrowed', models.PositiveIntegerField(default=0, verbose_name='الكتب المستعارة حالياً')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم (حساب الدخول)')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'الأعضاء',
                'db_table': 'members_member',
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإعارة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإرجاع')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='قيمة الغرامة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('returned', 'تم الإرجاع'), ('overdue', 'متأخر')], default='active', max_length=20, verbose_name='الحالة')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book', verbose_name='الكتاب')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='الموظف المسؤول')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='العضو')),
            ],
            options={
                'verbose_name': 'سجل إعارة',
                'verbose_name_plural': 'سجلات الإعارة',
                'db_table': 'borrowing_borrow',
            },
        ),
    ]
